In [7]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x)


tensor([5., 3.])


In [18]:
x = torch.zeros([3,5])
print (x)

print(x.shape)

y = torch.ones([5,5])
print(y)

y.shape

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([3, 5])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


torch.Size([5, 5])

In [20]:
y = torch.rand([5,4])
y

tensor([[0.8351, 0.1945, 0.4944, 0.3594],
        [0.8522, 0.0378, 0.0315, 0.5971],
        [0.7712, 0.6825, 0.8425, 0.2035],
        [0.5935, 0.3721, 0.7398, 0.9817],
        [0.1169, 0.3934, 0.0745, 0.1016]])

In [21]:
y.view([1,5*4])

tensor([[0.8351, 0.1945, 0.4944, 0.3594, 0.8522, 0.0378, 0.0315, 0.5971, 0.7712,
         0.6825, 0.8425, 0.2035, 0.5935, 0.3721, 0.7398, 0.9817, 0.1169, 0.3934,
         0.0745, 0.1016]])

In [25]:
#reassigning so that y takes the new shape
y = y.view([1,5*4])
y

RuntimeError: shape '[2, 1]' is invalid for input of size 20

## data pereparation: